version: '3'

services:
  my-anime:
    image: node:alpine
    container_name: my-anime
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - WHITELIST=my-anime.netlify.app,anime.carleslc.me,carleslc.me
      - REDIS_HOST=my-anime-redis-cache
      - NODE_ENV=production
      - PORT=3000
    links:
      - redis
    working_dir: /var/www/app
    command: sh -c 'npm i && node server.js'
  redis:
    image: redis
    container_name: my-anime-redis-cache
    expose:
      - 6379
